'use client';

import { ChangeEvent, useMemo, useState } from 'react';
import { Activity, BarChart3, BrainCircuit, Calculator, CheckCircle2, Database, Download, FileText, Filter, Globe2, Layers3, RefreshCw, Sparkles, Target, Upload, Zap } from 'lucide-react';

type Game={id:string;name:string;max:number;pick:number;focus:string[];source:string};
const games:Game[]=[
 // UK / National Lottery number games
 {id:'uk-lotto',name:'UK Lotto 6/59',max:59,pick:6,focus:['Main UK Lotto','Bonus number','Zones','Pairs/triplets'],source:'https://www.national-lottery.co.uk/games/lotto'},
 {id:'uk-euromillions',name:'EuroMillions 5/50 + 2/12',max:50,pick:5,focus:['Main numbers','Lucky Stars','Zones','Pairs/triplets'],source:'https://www.national-lottery.co.uk/games/euromillions'},
 {id:'uk-thunderball',name:'Thunderball 5/39 + 1/14',max:39,pick:5,focus:['Main numbers','Thunderball','Ending patterns','Zones'],source:'https://www.national-lottery.co.uk/games/thunderball'},
 {id:'uk-set-for-life',name:'Set For Life 5/59 + Life Ball',max:59,pick:5,focus:['Main numbers','Life Ball','Long windows','Pairs'],source:'https://www.national-lottery.co.uk/games/set-for-life'},
 {id:'uk-lotto-hotpicks',name:'Lotto HotPicks 1–59',max:59,pick:5,focus:['HotPicks','Number selection','Patterns','Backtesting'],source:'https://www.national-lottery.co.uk/games/lotto-hotpicks'},
 {id:'uk-euromillions-hotpicks',name:'EuroMillions HotPicks 1–50',max:50,pick:5,focus:['HotPicks','Main numbers','Patterns','Backtesting'],source:'https://www.national-lottery.co.uk/games/euromillions-hotpicks'},
 // Gosloto / Stoloto family
 {id:'3/15',name:'UK 49s 3/15 (15s)',max:15,pick:3,focus:['15s results','Pairs','Triplets','Last digits','Transitions'],source:'https://49s.co.uk/15s/results'},
 {id:'4/20',name:'Gosloto 4/20',max:20,pick:4,focus:['Field-ready','Zone balance','Pairs','Transitions'],source:'https://www.stoloto.ru/4x20'},
 {id:'5/36',name:'Gosloto 5/36',max:36,pick:5,focus:['5/36','Zones','Pairs/triplets','Ending transitions'],source:'https://www.stoloto.ru/5x36'},
 {id:'6/45',name:'Gosloto 6/45',max:45,pick:6,focus:['6/45','Zones','Pairs/triplets','Gap analysis'],source:'https://www.stoloto.ru/6x45'},
 {id:'7/49',name:'Gosloto 7/49',max:49,pick:7,focus:['7/49','5 zones','Pairs/triplets','Ending transitions'],source:'https://www.stoloto.ru/7x49'},
 {id:'rapido-8/20',name:'Rapido 8/20',max:20,pick:8,focus:['Rapido','Fast transitions','Last digits','Zone rotation'],source:''},
 {id:'12/24',name:'12/24',max:24,pick:12,focus:['12/24','Markov','Zones','Root/ending analysis'],source:''},
 {id:'20/80',name:'20/80',max:80,pick:20,focus:['20-number pool','8 zones','Ending balance','Multiple groups'],source:''}
];

const promptLibrary:Record<string,{title:string;prompt:string}[]>= {
 'Master AI':[{title:'Full Master Analysis',prompt:'Analyze the selected lottery using frequency, presence, gaps, skips, Markov transitions, pairs, triplets, zones, sections, roots, mirrors, last digits, odd/even, high/low, sums and historical windows. Rank the strongest research signals and explain each score. Do not claim certainty or guaranteed wins.'},{title:'Consensus Engine',prompt:'Run independent statistical, Markov, pattern, zone, pair/triplet and gap analyses. Combine them into a consensus ranking for the selected game and show where the models agree or disagree.'}],
 'Markov':[{title:'Markov Transition',prompt:'Build the draw-to-draw Markov transition matrix for the selected game. Identify the strongest observed transitions, transition frequencies and recent-vs-long-term differences. Backtest the transition rule on historical data.'},{title:'Markov + Zone',prompt:'Combine Markov movement with zone rotation. Identify transitions that repeatedly move between zones and create a ranked research pool without presenting it as a guaranteed prediction.'}],
 'Patterns':[{title:'Pattern Discovery',prompt:'Search the historical results for recurring pairs, triplets, last-digit structures, gaps, consecutive movements, mirrors, repeated numbers and zone structures. Rank patterns by frequency and persistence across multiple windows.'},{title:'Draw Movement',prompt:'Compare every draw with the previous draw. Measure repeats, replacements, skips, ±1/±2 movement, mirror movement, zone movement and ending movement. Summarize the most common transition structures.'}],
 'Wheels':[{title:'Wheel Optimizer',prompt:'Create a compact wheel from the selected pool. Maximize pair/triplet coverage subject to the selected ticket size and number limits. Report coverage counts and duplicate structures. This is a combinatorial coverage tool, not a winning guarantee.'},{title:'Ticket Filter',prompt:'Filter candidate tickets by configurable rules: odd/even balance, high/low balance, zone distribution, repeated endings, consecutive numbers, sum range, gap range and duplicate structures. Allow every filter to be switched on or off.'}],
 'Backtest':[{title:'Walk Forward',prompt:'Run a walk-forward backtest. For each historical draw, train only on earlier draws, generate the selected strategy pool, compare it with the actual next draw, and report average matches, best result, zero-match rate and distribution.'},{title:'Strategy Lab',prompt:'Compare Markov, frequency, zone, pair/triplet, gap, root and consensus strategies across historical windows. Rank strategies by backtest performance and stability, while clearly separating historical performance from future probability.'}],
 '3/15 15s':[{title:'15s Draw Analysis',prompt:'Analyze UK 49s 15s (3/15) historical draws using frequency, gaps, repeats, pair/triplet recurrence, last digits, odd/even, sums, zone movement and draw-to-draw transitions. Use only supplied historical results and separate historical observations from model signals.'},{title:'15s Next-Due Research',prompt:'For UK 49s 15s (3/15), rank a research pool using multiple independent signals: recent frequency, long-window frequency, gap/skip, Markov transition, pair/triplet support, last-digit structure and balance. Backtest the rule before ranking and never claim certainty.'}],
 'Research':[{title:'Anomaly Detector',prompt:'Detect unusual historical draws using sum, odd/even, zone, ending, gap, repetition and number-category structures. Label each draw normal, unusual or extreme and explain the evidence.'},{title:'Daily Report',prompt:'Create a daily LottoLab research report for the selected game: latest draw, historical window, top numbers by score, Markov transitions, zones, endings, pairs/triplets, candidate pools, wheel coverage, backtest results and warnings.'}]
};

const masterLottoPrompt=`LOTTOLAB — ULTIMATE MULTI-STRATEGY LOTTERY ANALYSIS ENGINE

You are LottoLab, an advanced statistical and combinatorial lottery-analysis system.

Analyze the selected lottery using only the historical draw data supplied. First validate the game format, number range, draw size, duplicates, missing/invalid rows and usable history. Never invent historical results.

Run the following stages in order: historical frequency/recency/gaps/skips/repetition/consecutive numbers/odd-even/high-low/sum/spread/clusters/zones/sections/last digits/roots/deltas; first-order Markov draw-to-draw transitions; zone rotation; section rotation including root and advanced root sections; recurring/delayed/transition pairs and triplets; cluster and macro-block movement; digital roots and last-digit structures; sorted-draw delta structures; parity/range balance; combinatorial coverage using BIBD/Steiner-style structures only where mathematically appropriate; configurable filters; multi-model scoring; consensus pools; diversified candidate generation; and walk-forward backtesting.

Default model weights: Markov 20%, Zone 15%, Section 15%, Pair 10%, Triplet 10%, Gap/Skip 10%, Odd/Even 5%, High/Low 5%, Last Digit 5%, Root/Delta 5%. Adjust weights only when walk-forward backtesting shows a more stable configuration.

Build Core, Secondary and Contrarian pools. Rank candidates with component scores and supporting-model counts. Diversify final combinations across zones, sections, ranges, parity, pair structures and delta structures.

For backtesting, use only information available before each target draw. Report 0/1/2/3/4/5/6+ match distributions as applicable, average matches, best/worst strategy, best weighting configuration and baseline comparison.

Final output: A) Data Quality B) Statistical Findings C) Markov Transitions D) Zone Structure E) Section Structure F) Core Pool G) Secondary Pool H) Candidate Combinations I) Diversified Wheel J) Backtest Results K) Strategy Performance L) Final Ranked Candidates. Clearly label historical observation, statistical signal, model output and backtested performance. Never claim a guaranteed outcome or that the model overcomes the randomness of a fair lottery.`;

const engineStages=[
 ['01','Data Validation','Validate format, range, draw size, missing rows and invalid values.'],
 ['02','Historical Analysis','Frequency, recency, gaps, skips, repetition, sums, spread and clustering.'],
 ['03','Markov Engine','Build draw-to-draw transition matrix and recent transition signals.'],
 ['04','Zone Engine','Adapt zones to the selected game and analyze rotation/structure.'],
 ['05','Section Engine','Analyze section frequency, rotation, root sections and advanced roots.'],
 ['06','Pair / Triplet','Measure recurring, delayed and transition pairs/triplets and coverage.'],
 ['07','Cluster / Macro','Analyze cluster movement, macro blocks and low/mid/high structures.'],
 ['08','Root / Ending','Analyze digital roots, last digits and ending transitions.'],
 ['09','Delta Engine','Compare sorted-number gaps and recurring delta structures.'],
 ['10','Balance Engine','Check parity, high/low, sum, spread, zone and section balance.'],
 ['11','Combinatorial','Build controlled wheels and coverage structures where appropriate.'],
 ['12','Filter Engine','Apply configurable consecutive, ending, cluster and balance filters.'],
 ['13','Consensus Engine','Combine independent model signals into Core/Secondary/Contrarian pools.'],
 ['14','Backtesting','Run rolling/walk-forward historical validation without future leakage.'],
 ['15','Final Ranking','Rank diversified candidates and explain supporting signals.']
];
function gameConfig(g:Game){const zoneCount=g.max<=20?4:g.max<=36?4:g.max<=49?5:6;const sectionCount=g.max<=20?4:g.max<=36?6:g.max<=49?7:8;return {zoneCount,sectionCount,zoneSize:Math.ceil(g.max/zoneCount),sectionSize:Math.ceil(g.max/sectionCount),pick:g.pick,range:`1–${g.max}`}}

const demo315=`3,5,14\n5,9,11\n7,11,14\n8,13,14\n4,10,13\n5,11,13\n4,9,10\n1,11,13\n3,6,10\n2,3,12\n1,7,13\n4,10,11\n1,9,10\n6,9,10\n8,12,13\n6,10,13`;
const weights=[['Frequency',25],['Multiple overlap',15],['Math categories',10],['Category overlap',10],['Zone',10],['Last digit',10],['Pair strength',8],['Triplet strength',5],['Transition/repeat',7]] as const;
function prime(n:number){if(n<2)return false;for(let i=2;i*i<=n;i++)if(n%i===0)return false;return true}
function square(n:number){return Number.isInteger(Math.sqrt(n))}
function cube(n:number){const r=Math.round(Math.cbrt(n));return r*r*r===n}
function triangular(n:number){return Number.isInteger(Math.sqrt(8*n+1))}
function fibonacci(n:number){return square(5*n*n+4)||square(5*n*n-4)}
function twin(n:number){return prime(n)&&(prime(n-2)||prime(n+2))}
function multis(n:number){const a:number[]=[];for(let k=2;k<=10;k++)if(n%k===0)a.push(k);return a}
function cats(n:number){return {prime:prime(n),square:square(n),cube:cube(n),triangular:triangular(n),fibonacci:fibonacci(n),twin:twin(n)}}
function catCount(n:number){return Object.values(cats(n)).filter(Boolean).length}
function zone(n:number,max:number){return Math.min(Math.floor((n-1)/10)+1,Math.ceil(max/10))}
function comb<T>(a:T[],k:number,limit=10000){const out:T[][]=[];const r=(s:number,c:T[])=>{if(out.length>=limit)return;if(c.length===k){out.push([...c]);return}for(let i=s;i<a.length;i++){c.push(a[i]);r(i+1,c);c.pop()}};r(0,[]);return out}
function parse(raw:string,g:Game){return raw.split(/\n|;/).map(x=>x.trim()).filter(Boolean).map(line=>line.replace(/<[^>]+>/g,' ').split(/[\s,|;:]+/).map(Number).filter(n=>Number.isInteger(n)&&n>=1&&n<=g.max)).map(a=>Array.from(new Set(a)).sort((x,y)=>x-y)).filter(a=>a.length===g.pick)}
function key(a:number[]){return [...a].sort((x,y)=>x-y).join('-')}
function analyze(draws:number[][],g:Game){
 const freq=Array(g.max+1).fill(0),presence=Array(g.max+1).fill(0),ends=Array(10).fill(0),endDraws=Array(10).fill(0),zones=Array(Math.ceil(g.max/10)+1).fill(0);const pairs=new Map<string,number>(),trips=new Map<string,number>(),quads=new Map<string,number>();
 draws.forEach(d=>{const es=new Set<number>();d.forEach(n=>{freq[n]++;presence[n]++;zones[zone(n,g.max)]++;es.add(n%10)});es.forEach(e=>{ends[e]++;endDraws[e]++});comb(d,2,500).forEach(p=>pairs.set(key(p),(pairs.get(key(p))||0)+1));if(d.length>=3)comb(d,3,500).forEach(t=>trips.set(key(t),(trips.get(key(t))||0)+1));if(d.length>=4)comb(d,4,500).forEach(q=>quads.set(key(q),(quads.get(key(q))||0)+1))});
 const maxF=Math.max(1,...freq),maxP=Math.max(1,...presence),maxE=Math.max(1,...ends),maxZ=Math.max(1,...zones);const maxPair=Math.max(1,...Array.from(pairs.values()),0),maxTrip=Math.max(1,...Array.from(trips.values()),0);
 const topPair=(n:number)=>Array.from(pairs.entries()).filter(([k])=>k.split('-').map(Number).includes(n)).sort((a,b)=>b[1]-a[1])[0]?.[1]||0;const topTrip=(n:number)=>Array.from(trips.entries()).filter(([k])=>k.split('-').map(Number).includes(n)).sort((a,b)=>b[1]-a[1])[0]?.[1]||0;
 const scores=Array.from({length:g.max},(_,i)=>i+1).map(n=>{const f=freq[n]/maxF*25,p=presence[n]/maxP*7,mo=Math.min(1,multis(n).length/4)*15,mc=Math.min(1,catCount(n)/3)*10,co=Math.min(1,catCount(n)/4)*10,z=zones[zone(n,g.max)]/maxZ*10,ld=ends[n%10]/maxE*10,ps=topPair(n)/maxPair*8,ts=topTrip(n)/maxTrip*5;return {n,score:Math.min(100,f+p+mo+mc+co+z+ld+ps+ts),freq:freq[n],presence:presence[n],ending:n%10,zone:zone(n,g.max),multi:multis(n),cats:cats(n),pair:topPair(n),trip:topTrip(n)}}).sort((a,b)=>b.score-a.score);
 const pattern3=new Map<string,number>(),pattern4=new Map<string,number>(),transition=new Map<number,number>();let retained=0,fullChange=0;for(let i=0;i<draws.length;i++){const distinct=Array.from(new Set(draws[i].map(n=>n%10)));if(distinct.length>=3)for(const c of comb(distinct,3,200))pattern3.set(key(c),(pattern3.get(key(c))||0)+1);if(distinct.length>=4)for(const c of comb(distinct,4,200))pattern4.set(key(c),(pattern4.get(key(c))||0)+1);if(i){const prev=new Set(draws[i-1].map(n=>n%10)),cur=new Set(draws[i].map(n=>n%10));let r=0;cur.forEach(e=>{if(prev.has(e))r++});transition.set(r,(transition.get(r)||0)+1);retained+=r;if(r===0)fullChange++}}
 return {freq,presence,ends,endDraws,zones,pairs,trips,quads,scores,pattern3,pattern4,transition,avgRetain:draws.length>1?retained/(draws.length-1):0,fullChange};
}
function topMap(m:Map<string,number>,n=10){return Array.from(m.entries()).sort((a,b)=>b[1]-a[1]).slice(0,n)}
function makeTicketScore(t:number[],a:ReturnType<typeof analyze>,g:Game){const rows=t.map(n=>a.scores[n-1]);const avg=rows.reduce((s,r)=>s+r.score,0)/rows.length;const primes=rows.filter(r=>r.cats.prime).length;const odds=t.filter(n=>n%2).length;const zs=new Set(t.map(n=>zone(n,g.max))).size;const es=new Set(t.map(n=>n%10)).size;const overlap=t.reduce((s,n)=>s+multis(n).length,0);const target=g.pick<=4?Math.max(1,Math.floor(g.pick/2)):Math.round(g.pick*.43);return {ticket:t,score:avg+Math.min(7,zs*1.1)+Math.min(5,es*.6)+Math.min(5,overlap*.25)-Math.abs(primes-target)*1.1-Math.abs(odds-g.pick/2)*.35}}
function generateTickets(pool:number[],g:Game,a:ReturnType<typeof analyze>){return comb(pool,g.pick,15000).map(t=>makeTicketScore(t,a,g)).sort((x,y)=>y.score-x.score).slice(0,30)}
function backtest(draws:number[][],g:Game){if(draws.length<6)return null;const rows:number[]=[];for(let i=5;i<draws.length;i++){const a=analyze(draws.slice(0,i),g);const top=a.scores.slice(0,Math.min(g.pick*3,g.max)).map(x=>x.n);rows.push(draws[i].filter(n=>top.includes(n)).length)}return {tests:rows.length,avg:rows.reduce((s,x)=>s+x,0)/rows.length,best:Math.max(...rows),dist:Object.entries(rows.reduce((o,x)=>{o[x]=(o[x]||0)+1;return o} as Record<string,number>,{})).sort((a,b)=>Number(a[0])-Number(b[0]))}}
function compareWindows(draws:number[][],g:Game){const windows=[10,12,20,50,100].filter(n=>draws.length>=Math.min(n,draws.length));return windows.map(w=>{const d=draws.slice(-w);const a=analyze(d,g);return {window:w,top:a.scores.slice(0,5).map(x=>x.n),topEnding:a.ends.map((c,digit)=>({digit,count:c})).sort((x,y)=>y.count-x.count)[0]?.digit??'—',retain:a.avgRetain,primeAvg:d.length?d.reduce((s,r)=>s+r.filter(prime).length,0)/d.length:0}})}

export default function Home(){
 const [gid,setGid]=useState('3/15');const g=games.find(x=>x.id===gid)!;const [raw,setRaw]=useState(demo315);const [tab,setTab]=useState('hotcold');const [promptCat,setPromptCat]=useState('Master AI');const [windowN,setWindowN]=useState(20);const [sourceUrl,setSourceUrl]=useState(g.source);const [sourceBusy,setSourceBusy]=useState(false);const [sourceMsg,setSourceMsg]=useState('');
 const drawsAll=useMemo(()=>parse(raw,g),[raw,g]);const draws=useMemo(()=>drawsAll.slice(-Math.min(windowN,drawsAll.length)),[drawsAll,windowN]);const a=useMemo(()=>analyze(draws,g),[draws,g]);const master=a.scores.slice(0,Math.min(g.max,20)).map(x=>x.n),core=a.scores.slice(0,Math.min(g.max,8)).map(x=>x.n),alt=a.scores.slice(8,Math.min(g.max,16)).map(x=>x.n),reserve=a.scores.slice(16,Math.min(g.max,24)).map(x=>x.n);const tickets=useMemo(()=>generateTickets(master,g,a),[master,g,a]);const bt=useMemo(()=>backtest(drawsAll,g),[drawsAll,g]);const endings=useMemo(()=>a.ends.map((count,digit)=>({digit,count,draws:a.endDraws[digit]})).sort((x,y)=>y.count-x.count),[a]);const p3=topMap(a.pattern3,10),p4=topMap(a.pattern4,10),pairsTop=useMemo(()=>topMap(a.pairs,20),[a]),tripsTop=useMemo(()=>topMap(a.trips,20),[a]),quadsTop=useMemo(()=>topMap(a.quads,20),[a]);const hot=useMemo(()=>[...a.scores].sort((x,y)=>y.freq-x.freq||y.score-x.score).slice(0,10),[a]);const cold=useMemo(()=>[...a.scores].sort((x,y)=>x.freq-y.freq||x.score-y.score).slice(0,10),[a]);const windows=useMemo(()=>compareWindows(drawsAll,g),[drawsAll,g]);const maxEnd=Math.max(1,...a.ends); const cfg=gameConfig(g);
 const fileLoad=(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{setRaw(String(r.result||''));setSourceMsg(`Imported ${f.name}`)};r.readAsText(f)};
 const changeGame=(id:string)=>{const ng=games.find(x=>x.id===id)!;setGid(id);setTab('overview');setWindowN(20);setRaw(id==='3/15'?demo315:'');setSourceUrl(ng.source);setSourceMsg('')};
 const fetchSource=async()=>{if(!sourceUrl)return;setSourceBusy(true);setSourceMsg('Fetching source…');try{const r=await fetch('/api/fetch-results',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:sourceUrl,max:g.max,pick:g.pick})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Fetch failed');setRaw(j.text);setSourceMsg(`Fetched source. Parsed ${parse(j.text,g).length} valid draws.`)}catch(e){setSourceMsg(e instanceof Error?e.message:'Fetch failed')}finally{setSourceBusy(false)}};
 const report=()=>{const data={version:'5.1',game:g.id,window:draws.length,totalLoaded:drawsAll.length,windows,master,core,alternative:alt,reserve,topNumbers:a.scores.slice(0,20),topEndings:endings.slice(0,10),top3EndingPatterns:p3,top4EndingPatterns:p4,pairs:pairsTop.slice(0,10),triplets:tripsTop.slice(0,10),quadruples:quadsTop.slice(0,10),hot:hot.map(x=>x.n),cold:cold.map(x=>x.n),transition:{averageRetained:a.avgRetain,fullChange:a.fullChange},tickets:tickets.slice(0,15).map(x=>x.ticket),backtest:bt};download(`lottolab-v4-${g.id.replace('/','-')}-report.json`,JSON.stringify(data,null,2),'application/json')};
 const csv=()=>{const rows=[['rank','number','score','frequency','drawPresence','ending','zone','multiples','prime','square','cube','triangular','fibonacci','twinPrime'],...a.scores.map((x,i)=>[i+1,x.n,x.score.toFixed(2),x.freq,x.presence,x.ending,x.zone,x.multi.join('|'),x.cats.prime,x.cats.square,x.cats.cube,x.cats.triangular,x.cats.fibonacci,x.cats.twin])];download(`lottolab-v4-${g.id.replace('/','-')}-numbers.csv`,rows.map(r=>r.join(',')).join('\n'),'text/csv')};
 return <div className="shell"><header className="top"><div className="brand"><div className="logo">LL</div><div><div className="title">LottoLab Master System <span className="v3">v5</span></div><div className="subtitle">Long-vs-recent research • source monitor • ending transitions • pools • tickets • walk-forward validation</div></div></div><div className="gamebar"><select value={gid} onChange={e=>changeGame(e.target.value)}><optgroup label="UK / National Lottery">{games.filter(x=>x.id.startsWith('uk-')).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</optgroup><optgroup label="Gosloto / Stoloto">{games.filter(x=>!x.id.startsWith('uk-')).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</optgroup></select><button onClick={()=>{setGid('3/15');setTab('overview');setWindowN(20);setRaw(demo315);setSourceUrl('https://49s.co.uk/15s/results');setSourceMsg('3/15 source selected')}}><Zap size={15}/> Load 3/15</button></div></header>
 <main className="main"><section className="hero"><div className="card heroCopy"><div className="eyebrow">MASTER RESEARCH ENGINE v5</div><h1>{g.name}: compare 100 → 50 → 20 → 12 → 10 draws</h1><p>Version 4 adds source monitoring, long-term versus recent comparison, regime checks, ending-transition research, pool overlap, ticket generation and walk-forward backtesting in one workflow.</p><div className="pills">{g.focus.map(x=><span className="pill" key={x}>{x}</span>)}</div></div><div className="card heroStats"><Stat n={draws.length} l="Draws in window"/><Stat n={drawsAll.length} l="Total loaded"/><Stat n={master.length} l="Master pool"/><Stat n={tickets.length} l="Ticket candidates"/></div></section>
 <div className="control card"><div><b>Load Results</b><span className="muted">Choose the latest 20, 50 or 100 loaded draws for analysis.</span></div><div className="windowBtns">{[20,50,100].map(n=><button className={windowN===n?'active':''} onClick={()=>setWindowN(n)} key={n}>{n}</button>)}</div><div className="actions"><label className="upload"><Upload size={15}/> Import CSV/TXT<input type="file" accept=".csv,.txt" onChange={fileLoad}/></label><button onClick={csv}><FileText size={15}/> Numbers CSV</button><button className="primary" onClick={report}><Download size={15}/> Full report</button></div></div>
 <section className="card source"><div className="sourceTop"><div><Head icon={<Globe2/>} title="Source monitor"/><p className="muted">Best-effort server fetch. If a site is JavaScript-rendered or blocks automated requests, paste/export its results instead.</p></div><div className="sourceStatus">{sourceMsg||'Ready'}</div></div><div className="sourceRow"><input value={sourceUrl} onChange={e=>setSourceUrl(e.target.value)} placeholder="Paste a public results page URL"/><button className="primary" disabled={sourceBusy||!sourceUrl} onClick={fetchSource}>{sourceBusy?<RefreshCw size={15} className="spin"/>:<Globe2 size={15}/>} {sourceBusy?'Fetching…':'Fetch results'}</button></div>{g.id==='3/15'&&<div className="callout"><b>UK 49s 15s source</b><p>LottoLab is configured to use the official 49s 15s results page for the 3/15 game. If the source is JavaScript-rendered or blocks server fetching, use the page to copy/export results and paste them into Historical Results.</p><a href="https://49s.co.uk/15s/results" target="_blank" rel="noreferrer">Open 49s 15s Results ↗</a></div>}</section>
 <div className="tabs">{[['overview','Overview'],['hotcold','🔥 Hot & Cold'],['numbers','⭐ Best Numbers'],['analysis','Pairs / Triplets / Quads'],['compare','Windows'],['endings','Last Digits'],['pools','Pools'],['tickets','Tickets'],['backtest','Backtest'],['master','Master Engine'],['prompts','AI Prompts'],['search','Google Search'],['system','System']].map(([id,label])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}>{label}</button>)}</div>
 {tab==='overview'&&<><div className="grid metrics"><Metric icon={<Database/>} value={draws.length} label="Draws analysed"/><Metric icon={<Target/>} value={a.scores[0]?.n??'—'} label="Top ranked number"/><Metric icon={<Layers3/>} value={a.scores[0]?.score.toFixed(1)??'—'} label="Top score / 100"/><Metric icon={<RefreshCw/>} value={a.avgRetain.toFixed(2)} label="Avg endings retained"/></div><div className="two"><section className="card"><Head icon={<BrainCircuit/>} title="Master score weights"/>{weights.map(([w,n])=><div className="weight" key={w}><span>{w}</span><div className="bar"><i style={{width:`${n*4}%`}}/></div><b>{n}%</b></div>)}<p className="muted">Weights are research features, not winning probabilities.</p></section><section className="card"><Head icon={<Activity/>} title="Current transition snapshot"/><div className="bigNumber">{a.avgRetain.toFixed(2)}</div><p className="muted">Average distinct last digits retained between consecutive draws in the selected window.</p><div className="transitionList">{Array.from(a.transition.entries()).sort((x,y)=>x[0]-y[0]).map(([k,v])=><div key={k}><span>{k} ending digits retained</span><b>{v}</b></div>)}</div></section></div><section className="card"><Head icon={<Sparkles/>} title="Top 12 ranked numbers"/><RankTable rows={a.scores.slice(0,12)}/></section></>}
 {tab==='compare'&&<section className="card"><Head icon={<BarChart3/>} title="Long-term vs recent windows"/><p className="muted">A pattern is more useful for research when it persists across multiple windows instead of appearing only in the latest few draws.</p><div className="tableWrap"><table><thead><tr><th>Window</th><th>Top 5</th><th>Top ending</th><th>Avg retained endings</th><th>Prime avg / draw</th></tr></thead><tbody>{windows.map(x=><tr key={x.window}><td><b>{x.window}</b></td><td>{x.top.join(', ')}</td><td>{x.topEnding}</td><td>{x.retain.toFixed(2)}</td><td>{x.primeAvg.toFixed(2)}</td></tr>)}</tbody></table></div><div className="two"><div className="callout"><b>Persistent signal</b><p>Numbers or ending structures that appear in both long and short windows deserve a higher research priority than a signal found only in one window.</p></div><div className="callout"><b>Recent regime</b><p>If the 10/12/20 windows differ sharply from 50/100, treat the short-term structure as a rotation regime rather than a stable rule.</p></div></div></section>}
 {tab==='hotcold'&&<><div className="two"><section className="card hotCard"><Head icon={<Sparkles/>} title="🔥 10 Hot Numbers"/><p className="muted">Highest appearance frequency in the selected results window.</p><div className="hotcoldGrid">{hot.map((x,i)=><div className="hcRow" key={x.n}><b>#{i+1}</b><span className="hcNumber hot">{x.n}</span><span>{x.freq} appearances</span><strong>{x.score.toFixed(1)}</strong></div>)}</div></section><section className="card coldCard"><Head icon={<RefreshCw/>} title="❄️ 10 Cold Numbers"/><p className="muted">Lowest appearance frequency in the selected results window.</p><div className="hotcoldGrid">{cold.map((x,i)=><div className="hcRow" key={x.n}><b>#{i+1}</b><span className="hcNumber cold">{x.n}</span><span>{x.freq} appearances</span><strong>{x.score.toFixed(1)}</strong></div>)}</div></section></div><section className="card"><Head icon={<Target/>} title="Hot / Cold methodology"/><p className="muted">Hot and cold are descriptive historical labels based on the selected 20, 50 or 100-draw window. They are not predictions and do not imply that a cold number is due.</p></section></> }
 {tab==='numbers'&&<section className="card"><Head icon={<Target/>} title="⭐ Best Numbers to Pick"/><p className="muted">Top-ranked research numbers using the current multi-factor score. Use the ranking as an analytical shortlist, not a guarantee.</p><RankTable rows={a.scores.slice(0,Math.min(20,g.max))}/></section>}
 {tab==='analysis'&&<><section className="card"><Head icon={<Layers3/>} title="Pairs Analysis"/><p className="muted">Most frequently recurring pairs in the selected result window.</p><Pattern rows={pairsTop.slice(0,15)}/></section><div className="two"><section className="card"><Head icon={<Layers3/>} title="Triplets Analysis"/><Pattern rows={tripsTop.slice(0,15)}/></section><section className="card"><Head icon={<Layers3/>} title="Quadruples Analysis"/><Pattern rows={quadsTop.slice(0,15)}/></section></div></> }
 {tab==='endings'&&<><section className="card"><Head icon={<RefreshCw/>} title="Last digit 0–9"/><div className="endingGrid">{endings.map(e=><div className="ending" key={e.digit}><div><b>{e.digit}</b><span>{e.count} appearances • {e.draws} draws</span></div><div className="bar"><i style={{width:`${e.count/maxEnd*100}%`}}/></div>)}</div></section><div className="two"><section className="card"><Head icon={<Filter/>} title="Top 3-ending patterns"/><Pattern rows={p3}/></section><section className="card"><Head icon={<Filter/>} title="Top 4-ending patterns"/><Pattern rows={p4}/></section></div><section className="card"><Head icon={<Activity/>} title="Ending transition"/><div className="grid"><Metric icon={<CheckCircle2/>} value={a.avgRetain.toFixed(2)} label="Average retained"/><Metric icon={<Zap/>} value={a.fullChange} label="Full ending changes"/><Metric icon={<Target/>} value={endings[0]?.digit??'—'} label="Top ending"/><Metric icon={<Layers3/>} value={endings.slice(0,3).map(x=>x.digit).join('–')} label="Top 3 endings"/></div></section></>}
 {tab==='pools'&&<><div className="poolStrip"><Pool title="Master" nums={master}/><Pool title="Core" nums={core}/><Pool title="Alternative" nums={alt}/></div><PoolCard title="Reserve" subtitle="Numbers ranked below the alternative pool for rotation/coverage." nums={reserve}/><section className="card"><Head icon={<Layers3/>} title="Pool overlap & rotation"/><div className="overlap"><b>{master.filter(n=>core.includes(n)).join(', ')||'None'}</b><span>Master ∩ Core</span></div><div className="overlap"><b>{alt.filter(n=>master.includes(n)).join(', ')||'None'}</b><span>Master ∩ Alternative</span></div><div className="overlap"><b>{core.filter(n=>alt.includes(n)).join(', ')||'None'}</b><span>Core ∩ Alternative</span></div></section></>}
 {tab==='tickets'&&<section className="card"><Head icon={<Target/>} title="Candidate ticket engine"/><p className="muted">Tickets are ranked for structural balance from the Master Pool. They are not forecasts or guarantees.</p><div className="ticketGrid">{tickets.map((t,i)=><div className="ticket" key={i}><div className="ticketTop"><span>Candidate #{i+1}</span><b>{t.score.toFixed(2)}</b></div><div className="ticketNums">{t.ticket.map(n=><span key={n}>{n}</span>)}</div><small className="muted">Prime {t.ticket.filter(n=>prime(n)).length} • Odd {t.ticket.filter(n=>n%2).length} • Endings {new Set(t.ticket.map(n=>n%10)).size} • Zones {new Set(t.ticket.map(n=>zone(n,g.max))).size}</small></div>)}</div></section>}
 {tab==='backtest'&&<section className="card"><Head icon={<CheckCircle2/>} title="Walk-forward backtest"/>{bt?<><div className="grid"><Metric icon={<Database/>} value={bt.tests} label="Tests"/><Metric icon={<Target/>} value={bt.avg.toFixed(2)} label="Average matches"/><Metric icon={<Sparkles/>} value={bt.best} label="Best match count"/><Metric icon={<BarChart3/>} value={`${bt.dist.find(([k])=>Number(k)===0)?.[1]??0}`} label="Zero-match tests"/></div><div className="tableWrap"><table><thead><tr><th>Matches</th><th>Tests</th></tr></thead><tbody>{bt.dist.map(([k,v])=><tr key={k}><td>{k}</td><td>{v}</td></tr>)}</tbody></table></div></>:<div className="notice">Load at least 6 draws for walk-forward testing.</div>}<div className="callout"><b>How to read this</b><p>Each test trains only on earlier draws. It measures historical matching performance of a broad ranked pool, not future winning probability.</p></div></section>}
 {tab==='master'&&<><section className="card masterDash"><Head icon={<Sparkles/>} title="LottoLab Ultimate Master Engine"/><p className="muted">Multi-stage dashboard: Master Engine → Markov → Zones → Sections → Pairs/Triplets → Roots/Endings → Delta → Balance → Combinatorial/Wheel → Consensus → Backtest.</p><div className="engineHeader"><div><b>{g.name}</b><span>Range {cfg.range} • Pick {cfg.pick} • {cfg.zoneCount} adaptive zones • {cfg.sectionCount} adaptive sections</span></div><button className="primary" onClick={()=>navigator.clipboard?.writeText(masterLottoPrompt)}>Copy Ultimate Master Prompt</button></div></section><div className="engineGrid">{engineStages.map(([n,title,desc],i)=><div className="engineStage" key={n}><div className="stageNum">{n}</div><div><b>{title}</b><p>{desc}</p></div><span className="stageStatus">{i<draws.length? 'READY':'WAITING'}</span></div>)}</div><section className="card"><Head icon={<Target/>} title="Consensus dashboard"/><div className="grid"><Metric icon={<Layers3/>} value={master.length} label="Core research pool"/><Metric icon={<BrainCircuit/>} value={a.scores.slice(0,5).map(x=>x.n).join(', ')} label="Top consensus numbers"/><Metric icon={<RefreshCw/>} value={a.avgRetain.toFixed(2)} label="Ending retention"/><Metric icon={<CheckCircle2/>} value={bt?.avg.toFixed(2)??'—'} label="Backtest avg matches"/></div><div className="two"><Pool title="Core Pool" nums={core}/><Pool title="Secondary Pool" nums={alt}/></div><div className="callout"><b>Model discipline</b><p>Consensus is an analytical ranking, not a probability guarantee. Historical backtest results are separated from future uncertainty.</p></div></section></>}

 {tab==='prompts'&&<section className="card"><Head icon={<BrainCircuit/>} title="LottoLab AI Prompt Library"/><p className="muted">Choose a prompt category, copy a prompt, then use it with your AI workflow. Prompts are research instructions and do not guarantee outcomes.</p><div className="tabs" style={{marginBottom:16}}>{Object.keys(promptLibrary).map(cat=><button className={cat===promptCat?'active':''} key={cat} onClick={()=>setPromptCat(cat)}>{cat}</button>)}</div><PromptList category={promptCat}/></section>}
 {tab==='search'&&<section className="card"><Head icon={<Globe2/>} title="Google Search Engine"/><p className="muted">Search Google for official results, strategy research, draw histories and other public information. LottoLab does not control Google's results.</p><GoogleSearch game={g.name}/><div className="callout"><b>Suggested search</b><p>Try: <code>{g.name} latest results</code>, <code>{g.name} historical results</code>, or <code>{g.name} lottery strategy</code>.</p></div></section>}
 {tab==='system'&&<section className="card"><Head icon={<Sparkles/>} title="LottoLab Ultimate Multi-Strategy System v5"/><div className="moduleGrid">{['Ultimate multi-strategy Master Prompt','15-stage Master Engine dashboard','Adaptive Game Configuration Engine','Source monitor / public-page fetch','Historical windows: 10 / 12 / 20 / 50 / 100','Long-term vs recent comparison','Frequency + draw presence','Prime / square / cube / triangular / Fibonacci / twin prime','Multiples ×2–×10 + multiple overlap','Last-digit 0–9 + 3/4-ending patterns','Ending retention + transition matrix','Odd/even + low/high + spacing','Zones + zone rotation','Pairs + triplets','Master / Core / Alternative / Reserve pools','Weighted Master Score','Candidate ticket engine','Walk-forward backtesting','JSON + CSV exports','Responsible modelling / no guarantees'].map((x,i)=><div className="module" key={x}><b>{String(i+1).padStart(2,'0')}</b><span>{x}</span></div>)}</div><div className="callout"><b>Important</b><p>Lottery outcomes are random. LottoLab measures historical structure and creates organized research selections; it does not establish a guaranteed predictive edge.</p></div></section>}
 <section className="card input"><div className="inputRow"><div><b>Historical results</b><p className="muted">One draw per line. Example: 3,5,14. The parser keeps valid rows for the selected game.</p></div><div className="actions"><button onClick={()=>setRaw('')}><RefreshCw size={15}/> Clear</button><button onClick={()=>setRaw(g.id==='3/15'?demo315:'')} className="primary"><Zap size={15}/> Load demo</button></div></div><textarea value={raw} onChange={e=>setRaw(e.target.value)} placeholder={`Paste ${g.pick} numbers per draw...`}/><div className="notice">Loaded <b>{drawsAll.length}</b> valid draws for {g.name}. Current analysis window: <b>{draws.length}</b>. Invalid/incomplete rows are ignored.</div></section>
 </main><footer className="footer">LottoLab Master System v5 • Historical research and educational use • Responsible play</footer></div>
}
function download(name:string,text:string,type:string){const blob=new Blob([text],{type});const url=URL.createObjectURL(blob);const el=document.createElement('a');el.href=url;el.download=name;el.click();URL.revokeObjectURL(url)}
function Stat({n,l}:{n:number|string;l:string}){return <div className="stat"><span>{l}</span><b>{n}</b></div>}
function Metric({icon,value,label}:{icon:React.ReactNode;value:React.ReactNode;label:string}){return <div className="card metricCard">{icon}<b>{value}</b><span>{label}</span></div>}
function Head({icon,title}:{icon:React.ReactNode;title:string}){return <div className="sectionHead"><div>{icon}<h2>{title}</h2></div></div>}
function Pool({title,nums}:{title:string;nums:number[]}){return <div className="pool"><b>{title}</b><div className="numberPills">{nums.map(n=><span key={n}>{n}</span>)}</div></div>}
function PoolCard({title,subtitle,nums}:{title:string;subtitle:string;nums:number[]}){return <section className="card"><Head icon={<Layers3/>} title={title}/><p className="muted">{subtitle}</p><div className="numberPills">{nums.map(n=><span key={n}>{n}</span>)}</div></section>}
function Pattern({rows}:{rows:[string,number][]}){return <div className="patternList">{rows.map(([k,v],i)=><div key={k}><b>#{i+1}</b><span>{k}</span><strong>{v}</strong></div>)}</div>}
function PromptList({category}:{category:string}){return <div className="moduleGrid">{promptLibrary[category].map((p,i)=><div className="module" key={p.title}><b>{String(i+1).padStart(2,'0')}</b><div><strong>{p.title}</strong><p className="muted">{p.prompt}</p><button className="primary" onClick={()=>navigator.clipboard?.writeText(p.prompt)}>Copy prompt</button></div></div>)}</div>}
function GoogleSearch({game}:{game:string}){const [q,setQ]=useState(`${game} latest results`);return <form className="inputRow" action="https://www.google.com/search" method="GET" target="_blank"><input name="q" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search Google…" style={{flex:1}}/><button className="primary" type="submit"><Globe2 size={15}/> Search Google</button></form>}
function RankTable({rows}:{rows:any[]}){return <div className="tableWrap"><table><thead><tr><th>#</th><th>Number</th><th>Score</th><th>Freq</th><th>Draws</th><th>End</th><th>Zone</th><th>Multiples</th><th>Math types</th></tr></thead><tbody>{rows.map((x,i)=><tr key={x.n}><td>{i+1}</td><td><b>{x.n}</b></td><td>{x.score.toFixed(2)}</td><td>{x.freq}</td><td>{x.presence}</td><td>{x.ending}</td><td>{x.zone}</td><td>{x.multi.length?x.multi.map((m:number)=>`×${m}`).join(' '):'—'}</td><td>{Object.entries(x.cats).filter(([,v])=>v).map(([k])=>k).join(', ')||'—'}</td></tr>)}</tbody></table></div>}
