'use client';
import { useMemo, useState } from 'react';

type Draw = number[];
type Game = { id: string; name: string; max: number; pick: number };
type Score = { n:number; score:number; freq:number; gap:number; odd:boolean; zone:number; last:number; pair:number; transition:number };

const games: Game[] = [
  {id:'7/49',name:'Gosloto 7/49',max:49,pick:7},{id:'6/45',name:'Gosloto 6/45',max:45,pick:6},
  {id:'5/36',name:'Gosloto 5/36',max:36,pick:5},{id:'4/20',name:'Gosloto 4/20',max:20,pick:4},
  {id:'3/15',name:'UK 49s 3/15',max:15,pick:3},{id:'8/20',name:'Rapido 8/20',max:20,pick:8},
  {id:'12/24',name:'12/24',max:24,pick:12},{id:'20/80',name:'20/80',max:80,pick:20}
];

function parse(raw:string,g:Game):Draw[]{
  return raw.split(/\n|;/).map(line=>Array.from(new Set((line.match(/\d+/g)||[]).map(Number).filter(n=>n>=1&&n<=g.max))).sort((a,b)=>a-b)).filter(d=>d.length>0);
}
function pairCount(draws:Draw[],a:number,b:number){return draws.reduce((s,d)=>s+(d.includes(a)&&d.includes(b)?1:0),0)}
function score(draws:Draw[],g:Game):Score[]{
  const f=Array(g.max+1).fill(0), gap=Array(g.max+1).fill(draws.length+1), trans=Array(g.max+1).fill(0);
  draws.forEach((d,i)=>{d.forEach(n=>{f[n]++;if(gap[n]===draws.length+1)gap[n]=draws.length-i});if(i>0)d.forEach(n=>draws[i-1].forEach(p=>{if(Math.abs(p-n)<=10)trans[n]++}))});
  const mf=Math.max(1,...f.slice(1)),mt=Math.max(1,...trans.slice(1)), recent=draws.slice(-Math.min(10,draws.length)), rf=Array(g.max+1).fill(0); recent.forEach(d=>d.forEach(n=>rf[n]++)); const mr=Math.max(1,...rf.slice(1));
  return Array.from({length:g.max},(_,i)=>{const n=i+1;const z=Math.floor((n-1)/Math.max(1,Math.ceil(g.max/5)))+1;const last=n%10;const pair=Math.max(0,...Array.from({length:g.max},(_,j)=>j+1).filter(x=>x!==n).map(x=>pairCount(draws,n,x)));const s=100*(.27*f[n]/mf+.23*rf[n]/mr+.18*trans[n]/mt+.12*Math.min(1,gap[n]/Math.max(1,draws.length))+.08*(n%2===0?1:.92)+.07*(pair/Math.max(1,draws.length))+.05*(1/(1+Math.abs(last-(draws.at(-1)?.at(-1)||last)%10))));return{n,score:s,freq:f[n],gap:gap[n],odd:n%2===1,zone:z,last,pair,transition:trans[n]};}).sort((a,b)=>b.score-a.score);
}

export default function AdvancedLab(){
 const [gid,setGid]=useState('7/49'); const g=games.find(x=>x.id===gid)||games[0];
 const [raw,setRaw]=useState(''); const [mode,setMode]=useState('Prediction'); const [windowSize,setWindowSize]=useState(50); const [pool,setPool]=useState(12);
 const draws=useMemo(()=>parse(raw,g),[raw,g]); const active=draws.slice(-windowSize); const scores=useMemo(()=>score(active,g),[active,g]);
 const primary=scores.slice(0,Math.min(pool,g.max)); const even=primary.filter(x=>!x.odd),odd=primary.filter(x=>x.odd);
 const test=useMemo(()=>{if(active.length<8)return{tested:0,avg:0,best:0};const hits:number[]=[];for(let i=5;i<active.length;i++){const prior=active.slice(0,i);const pred=score(prior,g).slice(0,Math.min(pool,g.max)).map(x=>x.n);hits.push(active[i].filter(n=>pred.includes(n)).length)}return{tested:hits.length,avg:hits.reduce((a,b)=>a+b,0)/hits.length,best:Math.max(...hits)}},[active,g,pool]);
 const loadDemo=()=>{const d=Array.from({length:Math.min(30,Math.max(10,windowSize))},(_,i)=>{const start=(i*3)%Math.max(1,g.max-g.pick+1)+1;return Array.from({length:g.pick},(_,j)=>((start+j*4+i)%g.max)+1)});setRaw(d.map(x=>x.join(' ')).join('\n'));};
 return <section className="adv">
  <div className="adv-head"><div><span className="eyebrow">LOTTOLAB • ADVANCED IMPROVEMENTS</span><h2>Strategy Laboratory</h2><p>Backtesting, ensemble scoring, prediction tracking and diagnostics in one workspace.</p></div><div className="tabs">{['Prediction','Strategy Lab','Backtesting','Diagnostics'].map(x=><button className={mode===x?'tab active':'tab'} onClick={()=>setMode(x)} key={x}>{x}</button>)}</div></div>
  <div className="controls"><label>Game<select value={gid} onChange={e=>setGid(e.target.value)}>{games.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>History window<select value={windowSize} onChange={e=>setWindowSize(+e.target.value)}>{[10,20,30,50,100].map(x=><option key={x}>{x}</option>)}</select></label><label>Candidate pool<input type="number" min={3} max={g.max} value={pool} onChange={e=>setPool(Math.max(3,+e.target.value||3))}/></label><button onClick={loadDemo}>Load test data</button><button onClick={()=>setRaw('')}>Clear</button><span className="status">{draws.length} valid draws</span></div>
  <textarea value={raw} onChange={e=>setRaw(e.target.value)} placeholder="Paste historical results — one draw per line"/>
  {mode==='Prediction'&&<div className="cards"><div className="panel"><h3>Ensemble candidate pool</h3><div className="balls">{primary.map(x=><button key={x.n} className="ball" title={`Score ${x.score.toFixed(1)}`}>{x.n}</button>)}</div><p className="hint">Scores combine frequency, recent presence, transitions, gap, parity, pair support and ending similarity. They are ranking signals, not winning probabilities.</p></div><div className="panel"><h3>Balanced line</h3><div className="line">{[...odd.slice(0,Math.ceil(g.pick/2)),...even.slice(0,Math.floor(g.pick/2))].slice(0,g.pick).map(x=><span key={x.n} className="ball selected">{x.n}</span>)}</div><p className="hint">Balanced odd/even candidate generated from the current pool.</p></div><div className="panel"><h3>Top evidence</h3>{scores.slice(0,7).map((x,i)=><div className="e-row" key={x.n}><b>#{i+1} {x.n}</b><span>{x.score.toFixed(1)}</span><small>F{x.freq} • G{x.gap} • T{x.transition} • P{x.pair}</small></div>)}</div></div>}
  {mode==='Strategy Lab'&&<div className="cards"><StrategyCard title="Frequency + Recent" text="Prioritises long-term frequency and the latest history window."/><StrategyCard title="Markov + Pairs" text="Weights transition observations and strongest pair support."/><StrategyCard title="Balanced Ensemble" text="Combines all available signals and parity balance."/><StrategyCard title="Coverage Strategy" text="Uses the candidate pool as input for wheel/coverage generation."/></div>}
  {mode==='Backtesting'&&<div className="cards"><div className="metric"><small>Walk-forward draws tested</small><strong>{test.tested}</strong></div><div className="metric"><small>Average candidate matches</small><strong>{test.avg.toFixed(2)}</strong></div><div className="metric"><small>Best historical match</small><strong>{test.best}</strong></div><div className="panel wide"><h3>How the test works</h3><p className="hint">For each target draw, LottoLab calculates the candidate pool using only draws before that target. It then counts matches against the target draw. This avoids using future information in the historical test.</p><div className="audit"><span>Data rows: {active.length}</span><span>Pool: {pool}</span><span>Game range: 1–{g.max}</span><span>Pick size: {g.pick}</span></div></div></div>}
  {mode==='Diagnostics'&&<div className="cards"><div className="metric"><small>Valid rows</small><strong>{draws.filter(d=>d.length>0).length}</strong></div><div className="metric"><small>Rows in analysis</small><strong>{active.length}</strong></div><div className="metric"><small>Range</small><strong>1–{g.max}</strong></div><div className="panel wide"><h3>Data quality checks</h3>{[{n:'Rows with valid numbers',v:`${draws.filter(d=>d.every(n=>n>=1&&n<=g.max)).length}/${draws.length}`},{n:'Duplicate values inside rows',v:draws.filter(d=>new Set(d).size!==d.length).length===0?'PASS':'CHECK'},{n:'Empty dataset',v:draws.length?'PASS':'WAIT'},{n:'Analysis readiness',v:active.length>=5?'READY':'NEED MORE DATA'}].map(x=><div className="check" key={x.n}><span>{x.n}</span><b>{x.v}</b></div>)}</div></div>}
  <footer>Lottery outcomes remain random. LottoLab provides structured historical research and backtesting, not guaranteed predictions.</footer>
  <style jsx>{`.adv{max-width:1200px;margin:18px auto 0;background:#091624;border:1px solid #28435f;border-radius:20px;padding:22px;color:#e7eef8}.adv-head{display:flex;justify-content:space-between;gap:16px;flex-wrap:wrap}.eyebrow{font-size:10px;letter-spacing:.16em;color:#64b5ff;font-weight:900}.adv h2{margin:5px 0}.adv p{color:#8fa6be;font-size:13px}.tabs{display:flex;gap:6px;flex-wrap:wrap}.tab,.controls button{background:#102338;color:#e7eef8;border:1px solid #294764;border-radius:8px;padding:9px 11px;font-weight:800;cursor:pointer}.tab.active{background:#123c62;border-color:#5aaeff}.controls{display:flex;gap:9px;align-items:end;flex-wrap:wrap;margin:16px 0}.controls label{display:grid;gap:4px;font-size:10px;color:#8fa6be}.controls select,.controls input{height:38px;background:#06111e;color:#e7eef8;border:1px solid #294764;border-radius:8px;padding:0 9px}.status{color:#7690a9;font-size:11px;padding-bottom:10px}.adv>textarea{width:100%;min-height:100px;background:#06111e;color:#dbeafe;border:1px solid #294764;border-radius:9px;padding:10px}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:10px}.panel,.metric{background:#0d1d2f;border:1px solid #223b56;border-radius:11px;padding:14px}.wide{grid-column:1/-1}.panel h3{margin:0 0 10px;font-size:14px}.balls,.line{display:flex;gap:8px;flex-wrap:wrap}.ball{width:38px;height:38px;border-radius:50%;border:1px solid #34597c;background:#132e49;color:#fff;font-weight:900}.ball.selected{background:#23c79a;color:#04130f;border-color:#23c79a}.hint{font-size:11px!important}.e-row,.check{display:grid;grid-template-columns:1fr auto;gap:6px;padding:7px 0;border-bottom:1px solid #1c3249}.e-row small{grid-column:1/-1;color:#718ba4;font-size:9px}.metric{display:grid;gap:5px}.metric small{color:#7e97af}.metric strong{font-size:26px}.audit{display:flex;gap:7px;flex-wrap:wrap}.audit span{border:1px solid #294764;border-radius:999px;padding:6px 8px;font-size:10px;color:#a9bed2}.adv footer{margin-top:12px;color:#607a92;font-size:10px}@media(max-width:800px){.cards{grid-template-columns:1fr}.wide{grid-column:auto}}`}</style>
 </section>
}
function StrategyCard({title,text}:{title:string;text:string}){const [on,setOn]=useState(true);return <div className="panel"><div style={{display:'flex',justifyContent:'space-between',gap:8}}><h3>{title}</h3><button className="tab" onClick={()=>setOn(!on)}>{on?'ON':'OFF'}</button></div><p>{text}</p><span style={{fontSize:10,color:on?'#55d7ae':'#768ba0'}}>{on?'Active signal':'Disabled signal'}</span></div>}
